### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by cescp** [Trouffman/octv_gears_lgp#2]
Link to Project Documentation is not working.
Could you please provide detailed compilation instructions?
I've tried:
- mkdir build
- cd build
- cmake ..
- make
but I get a lot of errors:
$ make
Scanning dependencies of target lgp_gears
[ 20%] Building C object CMakeFiles/lgp_gears.dir/src/full_logic-func.c.o
/disc/src/octv_gears_lgp/src/full_logic-func.c:1:31: error: expected ‘)’ before numeric constant
 writecommand_va(camerahandle, 12, 0x01, 0x01, 0x01, 0x00, 0x1C, 0x08, 0x00, 0x00, 0x00, 0x40, 0x00, 0x00);
                               ^
...

**Comment by Trouffman** [comment]
The code is not functional and I d not have the Device anymore to test.

**Comment by cescp** [comment]
Do you know about any other similar project?

**Comment by Trouffman** [comment]
not from what I remenber. There was one for the Elgato device but not sure where it was either.

**Comment by machinedgod** [comment]
Just to add - the last commit by me (12d8c9f364bfa03f4b27fc6ffb67a53c03eee2b8) was successfully buildable for sure. It might be useful to branch off at that point and add whatever is missing.

While I was still on this project, we got through device initialization, but not much further, since we both ran out of time, and out of the device :-D as Trouff said.

**Comment by davilico05** [comment]
Any instructions of use ?

**Comment by Trouffman** [comment]
@davilico05 sadly nothing more is available than the one in the latest commit.

That project was cancelled and the sources are up here for people to build upon.

As the device itself is End-of-life, for a while already. NO point in spending more time on it. I would suggest yo look for a USB HDMI Capture with UVC Support. :)
